# Generated by Django 6.0.3 on 2026-03-18 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pessoa_renda_mensal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='renda_mensal',
        ),
        migrations.AlterField(
            model_name='transacao',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transacoes', to='core.pessoa'),
        ),
        migrations.CreateModel(
            name='RendaMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('valor_liquido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pessoa')),
            ],
            options={
                'unique_together': {('pessoa', 'mes', 'ano')},
            },
        ),
    ]
