# Generated by Django 6.0.3 on 2026-03-19 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_instituicao_cofre'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoCofre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Depósito (Loot)'), ('saida', 'Saque (Resgate)')], max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.CharField(blank=True, choices=[('pessoal', 'Gasto Pessoal / Lazer'), ('saude', 'Saúde / Farmácia'), ('casa', 'Despesas da Casa / Manutenção'), ('emergencia', 'Emergência Imprevista'), ('objetivo', 'Objetivo Concluído! (GG)'), ('outro', 'Outros Motivos')], max_length=20, null=True)),
                ('cofre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cofre')),
            ],
        ),
    ]
