# Generated by Django 6.0.3 on 2026-03-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_historicocofre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicocofre',
            name='tipo',
            field=models.CharField(choices=[('entrada', 'Depósito (Loot)'), ('saida', 'Saque (Resgate)'), ('reposicao', 'Reposição de Dívida')], max_length=10),
        ),
    ]
