# Generated by Django 6.0.3 on 2026-03-19 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_historicocofre_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='avatares/'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='xp_atual',
            field=models.IntegerField(default=0),
        ),
    ]
