# Generated by Django 6.0.3 on 2026-03-24 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_pessoa_foto_perfil_pessoa_level_pessoa_xp_atual'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='ultimo_mes_fechado',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
