# Generated by Django 6.0.3 on 2026-03-25 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_pessoa_ultimo_mes_fechado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='meses_fechados',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
