# Generated by Django 6.0.3 on 2026-04-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_mestreseguranca'),
    ]

    operations = [
        migrations.AddField(
            model_name='mestreseguranca',
            name='gemini_api_key',
            field=models.CharField(blank=True, help_text='Chave da IA para extrair PDFs', max_length=255, null=True),
        ),
    ]
