# Generated by Django 6.0.3 on 2026-04-06 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_mestreseguranca_gemini_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='mestreseguranca',
            name='dias_backup',
            field=models.CharField(blank=True, help_text='0,1,2,3,4,5,6', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mestreseguranca',
            name='diretorio_backup',
            field=models.CharField(blank=True, help_text='Caminho do HD ou Google Drive', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='mestreseguranca',
            name='frequencia_backup',
            field=models.CharField(default='MANUAL', max_length=20),
        ),
        migrations.AddField(
            model_name='mestreseguranca',
            name='horario_backup',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
