# Generated by Django 6.0.3 on 2026-04-06 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_mestreseguranca_dias_backup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mestreseguranca',
            name='gemini_api_key',
            field=models.CharField(blank=True, help_text='Chave da IA para extrair PDFs', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mestreseguranca',
            name='resposta_secreta',
            field=models.CharField(max_length=500),
        ),
    ]
