# Generated by Django 6.0.3 on 2026-04-07 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_mestreseguranca_gemini_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='tutorial_visto',
            field=models.BooleanField(default=False),
        ),
    ]
