# Generated by Django 6.0.5 on 2026-05-05 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_pessoa_tutorial_visto'),
    ]

    operations = [
        migrations.AddField(
            model_name='mestreseguranca',
            name='ai_default',
            field=models.CharField(choices=[('GEMINI', 'Gemini (Google)'), ('GROQ', 'Groq (Llama)')], default='GEMINI', max_length=20),
        ),
        migrations.AddField(
            model_name='mestreseguranca',
            name='groq_api_key',
            field=models.CharField(blank=True, help_text='Chave da IA Groq (Llama)', max_length=500, null=True),
        ),
    ]
