# Generated by Django 6.0.5 on 2026-05-06 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_mestreseguranca_ai_default_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DespesaRecorrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(help_text='Ex: Conta de Luz', max_length=255)),
                ('valor_estimado', models.DecimalField(decimal_places=2, help_text='Valor aproximado ou fixo da conta', max_digits=10)),
                ('dia_vencimento', models.IntegerField(default=10, help_text='Dia de vencimento (1 a 31)')),
                ('cartao', models.ForeignKey(blank=True, help_text='Opcional. Deixe em branco se for Pix/Boleto.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cartaocredito')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroRecorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('data_geracao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('mes', 'ano')},
            },
        ),
    ]
