# Generated by Django 6.0.7 on 2026-08-04 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_despesarecorrente_registrorecorrencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='classe_atual',
            field=models.CharField(default='Aventureiro', max_length=50),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='orcamento_mensal',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='HP Base do Mês (Para Owner)', max_digits=10),
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ex: Cortar o Ifood', max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('meta_valor', models.DecimalField(decimal_places=2, help_text='Limite de gastos (HP do Boss)', max_digits=10)),
                ('recompensa_xp', models.IntegerField(default=500, help_text='XP para a Party se vencer o boss')),
                ('mes_vigencia', models.IntegerField()),
                ('ano_vigencia', models.IntegerField()),
                ('categoria_alvo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='QuestStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE', 'Em combate (Pendente)'), ('VENCIDA', 'Vitória! Boss derrotado'), ('PERDIDA', 'Derrota! Party aniquilada')], default='PENDENTE', max_length=20)),
                ('valor_gasto_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('quest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='core.quest')),
            ],
        ),
        migrations.CreateModel(
            name='Rateio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rateios', to='core.pessoa')),
                ('transacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rateios', to='core.transacao')),
            ],
        ),
    ]
