# Generated by Django 6.0.5 on 2026-09-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_pessoa_classe_atual_pessoa_orcamento_mensal_quest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mestreseguranca',
            name='groq_model_override',
            field=models.CharField(blank=True, help_text='Modelo Groq específico (deixe vazio para auto-detecção)', max_length=100, null=True),
        ),
    ]
