# Generated by Django 6.0.3 on 2026-09-30 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_mestreseguranca_groq_model_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartaocredito',
            name='pluggy_account_id',
            field=models.CharField(blank=True, help_text='ID da Conta no Pluggy', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='mestreseguranca',
            name='pluggy_client_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='mestreseguranca',
            name='pluggy_client_secret',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='transacao',
            name='pluggy_id',
            field=models.CharField(blank=True, help_text='ID da transação no Pluggy', max_length=150, null=True, unique=True),
        ),
    ]
